### ISSUE TITLE
fibjs如何使用node的包

### ISSUE THREAD

**Issue by coolicer** [xwcoder/eox#1]
.modules是fibjs放包的位置吗？还是从node_modules做一个软链出来？

**Comment by xwcoder** [comment]
@coolicer fibjs的包放都在.modules文件夹下  就像nodejs都放在node_modules下一样；
这个demo里的ejs我是npm直接安装的，所以在node_modules下，直接软链了一下在fibjs中用。

**Comment by coolicer** [comment]
@xwcoder 我弄好了，你的ejs是改过的吗?我拷过去就能跑了。啥都没，fibjs好难进行下去。我看中一些好的东西　，但是生态少得可怜。

**Comment by xwcoder** [comment]
@coolicer 嗯，demo里的ejs是改过的。fibjs生态跟nodejs是没法比啊
